# Docker


# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  image: "hsulimann/golang-restapi"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-hsulimann'
        repository: 'hsulimann/golang-restapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - script: |
        helm repo add --username henrique.sulimann@gmail.com --password $(GITHUB-TOKEN)  hsulimann-repository https://henrique-sulimann.github.io/helm-repository/
        helm repo update
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'hsulimann-aks'
        namespace: 'default'
        command: 'upgrade'
        chartType: 'Name'
        chartName: 'hsulimann-repository/golang-restapi'
        releaseName: 'golang-restapi'
        overrideValues: 'golang.image=$(image):$(tag)'
