# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  image: "hsulimann/golang-restapi"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          hsulimann/$(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-hsulimann'
        repository: 'hsulimann/golang-restapi'
        command: 'push'
        tags: '$(Build.BuildId)'
